version: '3.9'
services:
  db:
    image: postgres
    container_name: db
    # volumes:
      # - ./db_init:/docker-entrypoint-initdb.d
      # - db_data:/var/lib/postgresql/data
    environment:
      # POSTGRES_PASSWORD: 666
      POSTGRES_USER: postgres
      POSTGRES_DB: ectest
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    # networks:
    #   - encost
    ports:
      - "127.0.0.60:5432:5432"
    secrets:
      - postgres_password

volumes:
  db_data:
    driver: local

# networks:
#   django_survey:
#     driver: bridge
#     name: encost
#     external: true

secrets:
  postgres_password:
    file: ./secrets/postgres_password
